server:
  port: 8080


#AutoConfiguration에서 오버라이딩 가능하게 설정
spring:

  main:
    allow-bean-definition-overriding: true
    
  #H2 DB 사용설정
  h2:
     console:
       enabled: true
       path: /h2-console
       
  datasource:
    url: jdbc:h2:~/local
    driverClassName: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #이상은 repository의 메소드가 호출될 때 JPA에서 실제 실행되는 쿼리를 보기위해 로그를 남기는 코드
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
  
  #변경사항 실시간 반영
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
   
      